# Name of the application
spring.application.name=ems-backend

# JDBC URL to connect to your online MySQL database
spring.datasource.url=jdbc:mysql://sql213.infinityfree.com:3306/if0_39604100_employeedb

# MySQL user credentials (use your vPanel password as the password)
spring.datasource.username=if0_39604100
spring.datasource.password=22P31a0525

# Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
